CREATE DATABASE sm_edu DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

flush privileges;

CREATE TABLE IF NOT EXISTS user_t (
	`id`	INT UNSIGNED	NOT NULL AUTO_INCREMENT PRIMARY KEY ,
	`userName`	VARCHAR(64)	NOT NULL ,
	`password`	VARCHAR(64)	NOT NULL ,
	`age`	MEDIUMINT UNSIGNED	NOT NULL
) /*! DEFAULT CHARACTER SET=utf8 COLLATE=utf8_bin COMMENT='”√ªß±Ì' */;